package:
  name: ollama
  version: 0.5.4
source:
  path: /data/users/krmartin/src/kmart-dev/ollama-feedstock/recipe/ollama-linux-amd64.tgz
build:
  number: '0'
  script: 'mkdir -p $PREFIX/bin

    mkdir -p $PREFIX/lib

    tar -xzf $SRC_DIR/ollama-linux-amd64.tgz -C $SRC_DIR

    patchelf --set-rpath $PREFIX/lib $SRC_DIR/bin/ollama

    mv $SRC_DIR/bin/* $PREFIX/bin/

    mv $SRC_DIR/lib/* $PREFIX/lib/

    '
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - libgomp 14.2.0 h77fa898_1
    - _openmp_mutex 4.5 2_gnu
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libstdcxx 14.2.0 hc0a3c3a_1
    - libstdcxx-ng 14.2.0 h4852527_1
    - patchelf 0.17.2 h58526e2_0
  run: []

test:
  commands:
    - ollama --version
    - ollama --help

about:
  home: http://example.com
  license: MIT
  summary: A brief summary of the package.
  description: |
    **Note:** This package uses pre-built binaries from https://github.com/ollama/ollama/releases.
    Building from source is not currently supported.

extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - kmart-dev

