package:
  name: ollama
  version: "0.5.4"

source:
  url: v0.5.4/ollama-linux-amd64.tgz

build:
  number: 0
  script: |
    mkdir -p $PREFIX/bin
    mkdir -p $PREFIX/lib
    tar -xzf $SRC_DIR/ollama-linux-amd64.tgz -C $SRC_DIR
    patchelf --set-rpath $PREFIX/lib $SRC_DIR/bin/ollama
    mv $SRC_DIR/bin/* $PREFIX/bin/
    mv $SRC_DIR/lib/* $PREFIX/lib/

requirements:
  build:
    - patchelf

about:
  home: http://example.com
  license: MIT
  summary: A brief summary of the package.

extra:
  recipe-maintainers:
    - kmart-dev
